### PR TITLE
Add Travis build

### LINKED ISSUE #1: Add Travis build

### PR DESCRIPTION
**Pull request by kakao-jun-e**
Fixed #1

### CODE REVIEW

**Comment by remagpie** [comment]
Have you tested it on your forked repository?

**Comment by kakao-jun-e** [comment]
@Kais-DkM Pls, take a look https://travis-ci.org/redongjun/codechain-miner

**Comment by remagpie** [comment]
It seems current code is not correctly formatted.
Please add additional commit for fixing code formats.

**Comment by remagpie** [comment]
Please remove dot from commit message in https://github.com/CodeChain-io/codechain-miner/pull/2/commits/00fa43702b670a6e37a5bec9f7f05e37079e8972

**Pull request merged**
